name: Backend Coverage

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: code/backend/getactivecore

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./code/backend/getactivecore/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
