name: "Code Scanning"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Setup JDK
      if: matrix.language == 'java'
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Setup Gradle
      if: matrix.language == 'java'
      uses: gradle/gradle-build-action@v2

    - name: Build Java Code
      if: matrix.language == 'java'
      working-directory: ./code/backend/getactivecore
      run: |
        ./gradlew build -x test

    - name: Setup Node.js
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './code/frontend/package-lock.json'

    - name: Build JavaScript Code
      if: matrix.language == 'javascript'
      working-directory: ./code/frontend/
      run: |
        npm install
        npm run build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{ matrix.language }}" 