name: CI workflow

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run backend coverage
        working-directory: ./code/backend/getactivecore
        run: |
          ./gradlew jacocoTestReport

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate coverage JSON badge
        run: |
          pip install lxml
          python ../../.github/scripts/extract_coverage_and_generate_badge.py
        working-directory: ./
